-- Calendrier Équipe MDL v0.9.0
-- OPTIONNEL : journal d'administration minimal
-- La v0.9.0 fonctionne SANS ce SQL.
-- Exécuter uniquement si tu veux activer le journal dès maintenant.

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;

drop policy if exists "audit_admin_read" on public.admin_audit_log;
create policy "audit_admin_read"
on public.admin_audit_log for select
to authenticated
using (public.is_admin());

revoke all on public.admin_audit_log from anon;
grant select on public.admin_audit_log to authenticated;
